image: golang:1.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- test
- build

before_script:
- mkdir -p .gopath
- export GOPATH=$(pwd)/.gopath

vet:
  stage: test
  script:
  - make vet
  cache:
    key: go1.11
    paths:
    - .gopath

test:
  stage: test
  script:
  - make test
  cache:
    key: go1.11
    paths:
    - .gopath

build:
  only:
  - master
  stage: build
  tags:
  - docker
  image: docker:stable
  services:
  - docker:dind
  script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build --pull -t eventter/mq -f mq/Dockerfile .
  - docker push eventter/mq

build_web:
  only:
  - master
  stage: build
  image: debian:stable
  script:
  - apt-get update
  - apt-get install --no-install-recommends --no-install-suggests ca-certificates git openssh-client wget -y
  - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb -O /tmp/hugo.deb
  - dpkg -i /tmp/hugo.deb
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - echo "$WEB_SSH_PRIVATE_KEY" | ssh-add - > /dev/null
  - git config --global user.email hi@eventter.io
  - git config --global user.name "Gitlab CI"
  - cd web
  - git clone git@github.com:eventter/eventter.github.io.git public
  - hugo
  - cd public
  - git add .
  - if git diff --cached --exit-code > /dev/null; then exit 0; fi # no changes
  - '{ echo "$CI_COMMIT_TITLE"; echo; echo "eventter/eventter#$CI_COMMIT_SHA"; } | git commit -F -'
  - git push origin master
