image: golang:1.11

stages:
- test
- build

vet:
  stage: test
  script:
  - make vet

test:
  stage: test
  script:
  - make test

build:
  stage: build
  tags:
  - docker
  image: docker:stable
  services:
  - docker:dind
  script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build --pull -t eventter/mq -f mq/Dockerfile .
  - docker push eventter/mq
