baseURL = "https://eventter.io/"
languageCode = "en-us"
title = "EventterMQ"
theme = "kube"
pygmentsCodeFences = true
pygmentsStyle = "github"

[params]
Author = "Jakub Kulhan"
InceptionYear = "2018"

[[menu.main]]
name = "Docs"
weight = 100
url = "/docs/"
[[menu.main]]
name = "GitHub"
weight = 100
url = "https://github.com/eventter/eventter"
